### ISSUE TITLE
Human readable file sizes

### ISSUE THREAD

**Issue by jaredmoody** [wdas/reposado#16]
Would you consider a quick change or a patch for some more human readable output?

I'd like to see this:

    Downloading 1126391 bytes from http://swscan.apple.com/content/catalogs/index.sucatalog...
    301 products found in http://swscan.apple.com/content/catalogs/index.sucatalog
    Downloading 14818 bytes from http://swcdn.apple.com/content/downloads/20/44/041-   7449/w8gzvftbg47l4ozr8fhm8h75073wlb1t4u/Aperture3.4.1Update.smd...
    Downloading 578113722 bytes from http://swcdn.apple.com/content/downloads/20/44/041-7449/w8gzvftbg47l4ozr8fhm8h75073wlb1t4u/Aperture3.4.1Update.pkg.

Turned into this:

    Downloading 1 MB from http://swscan.apple.com/content/catalogs/index.sucatalog...
    301 products found in http://swscan.apple.com/content/catalogs/index.sucatalog
    Downloading 1.4 kB from http://swcdn.apple.com/content/downloads/20/44/041-7449/w8gzvftbg47l4ozr8fhm8h75073wlb1t4u/Aperture3.4.1Update.smd...
    Downloading 551 MB from http://swcdn.apple.com/content/downloads/20/44/041-7449/w8gzvftbg47l4ozr8fhm8h75073wlb1t4u/Aperture3.4.1Update.pkg.

**Comment by n8felton** [comment]
The discussion appears to have happened at https://groups.google.com/d/topic/reposado/yPTePXbqz3E/discussion, but @timsutton was the only person that really weighed in.

Personally, I like the idea of having it be an option in the preferences.plist as Tim suggested.

**Comment by gregneagle** [comment]
It's been over three years and not much traction, let alone anyone offering to write code...

**Comment by n8felton** [comment]
Meh, I'm just getting around to using Reposado over a native OS X Server SUS and was checking out the Issues and PRs on the project. Just thought I'd through my 2 cents in there and bring the topic up again.

**Comment by jessepeterson** [comment]
Feature implemented as part of PR #48, issue can be closed now. :smile:
