### ISSUE TITLE
Some content does not get downloaded

### ISSUE THREAD

**Issue by spitfire** [wdas/reposado#19]
I've tried repo_sync several times, and there is some file that don't get downloaded.

$ repo_sync
repo_sync run started
283 products found in http://swscan.apple.com/content/catalogs/index.sucatalog
Building index.sucatalog...
186 products found in http://swscan.apple.com/content/catalogs/index-1.sucatalog
Building index-1.sucatalog...
283 products found in http://swscan.apple.com/content/catalogs/others/index-leopard.merged-1.sucatalog
Building index-leopard.merged-1.sucatalog...
360 products found in http://swscan.apple.com/content/catalogs/others/index-leopard-snowleopard.merged-1.sucatalog
Building index-leopard-snowleopard.merged-1.sucatalog...
586 products found in http://swscan.apple.com/content/catalogs/others/index-lion-snowleopard-leopard.merged-1.sucatalog
Could not replicate http://swcdn.apple.com/content/downloads/11/05/041-0925/g27es04pw9re5ggrfp3vuf8ew6r53asfz8/041-0925.English.dist: HTTP result 200: OK
Error reading /reposado/data/content/downloads/11/05/041-0925/g27es04pw9re5ggrfp3vuf8ew6r53asfz8/041-0925.English.dist: [Errno 2] No such file or directory: '/reposado/data/content/downloads/11/05/041-0925/g27es04pw9re5ggrfp3vuf8ew6r53asfz8/041-0925.English.dist'
Could not get data from dist file: /reposado/data/content/downloads/11/05/041-0925/g27es04pw9re5ggrfp3vuf8ew6r53asfz8/041-0925.English.dist
Building index-lion-snowleopard-leopard.merged-1.sucatalog...
WARNING: did not add product 041-0925 to catalog index-lion-snowleopard-leopard.merged-1.sucatalog.apple because it has not been downloaded.
358 products found in http://swscan.apple.com/content/catalogs/others/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Could not replicate http://swcdn.apple.com/content/downloads/11/05/041-0925/g27es04pw9re5ggrfp3vuf8ew6r53asfz8/041-0925.English.dist: HTTP result 200: OK
Error reading /reposado/data/content/downloads/11/05/041-0925/g27es04pw9re5ggrfp3vuf8ew6r53asfz8/041-0925.English.dist: [Errno 2] No such file or directory: '/reposado/data/content/downloads/11/05/041-0925/g27es04pw9re5ggrfp3vuf8ew6r53asfz8/041-0925.English.dist'
Could not get data from dist file: /reposado/data/content/downloads/11/05/041-0925/g27es04pw9re5ggrfp3vuf8ew6r53asfz8/041-0925.English.dist
Building index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog...
WARNING: did not add product 041-0925 to catalog index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.apple because it has not been downloaded.
repo_sync run ended

**Comment by gregneagle** [comment]
Closing this old issue
