### ISSUE TITLE
Unknown cipher in list

### ISSUE THREAD

**Issue by igroykt** [wdas/reposado#35]
Have some problem with sync.
Reposado output:
>[root@share code]# ./repo_sync 
repo_sync run started
280 products found in http://swscan.apple.com/content/catalogs/index.sucatalog
Building index.sucatalog...
Building index_osx.sucatalog...
186 products found in http://swscan.apple.com/content/catalogs/index-1.sucatalog
Building index-1.sucatalog...
Building index-1_osx.sucatalog...
280 products found in http://swscan.apple.com/content/catalogs/others/index-leopard.merged-1.sucatalog
Building index-leopard.merged-1.sucatalog...
Building index-leopard.merged-1_osx.sucatalog...
359 products found in http://swscan.apple.com/content/catalogs/others/index-leopard-snowleopard.merged-1.sucatalog
Building index-leopard-snowleopard.merged-1.sucatalog...
Building index-leopard-snowleopard.merged-1_osx.sucatalog...
585 products found in http://swscan.apple.com/content/catalogs/others/index-lion-snowleopard-leopard.merged-1.sucatalog
Could not replicate http://swcdn.apple.com/content/downloads/10/21/031-12109/o0mghmdsr9638ac0ydmnxqnlzkkqaxsvi1/MacBookAirMid2012SoftwareUpd1.0.dst/031-12109.sk.dist: HTTP result 200: OK
Building index-lion-snowleopard-leopard.merged-1.sucatalog...
Building index-lion-snowleopard-leopard.merged-1_osx.sucatalog...
427 products found in http://swscan.apple.com/content/catalogs/others/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Building index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog...
Building index-mountainlion-lion-snowleopard-leopard.merged-1_osx.sucatalog...
Could not replicate https://swscan.apple.com/content/catalogs/others/index-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog: Error 59: Unknown cipher in list: HIGH
Could not replicate https://swscan.apple.com/content/catalogs/others/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog: Error 59: Unknown cipher in list: HIGH
Could not replicate https://swscan.apple.com/content/catalogs/others/index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog: Error 59: Unknown cipher in list: HIGH
repo_sync run ended

But links seems to be working:
>wget https://swscan.apple.com/content/catalogs/others/index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
--2015-10-11 11:35:01--  https://swscan.apple.com/content/catalogs/others/index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Распознаётся swscan.apple.com (swscan.apple.com)… 17.164.1.22
Подключение к swscan.apple.com (swscan.apple.com)|17.164.1.22|:443... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа... 200 OK
Длина: 4325608 (4,1M) [application/x-apple-plist]
Сохранение в: «index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.2»

>index-10.11-10.10-10.9-mountainlion-lion-snowleopard 100%[=======================================================================================================================>]   4,12M   167KB/s   за 29s    

>2015-10-11 11:35:31 (146 KB/s) - «index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.2» сохранён [4325608/4325608]

>tail -n5 index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
                        <string>45a9dc67381d81b4af460c703b0dded9d4a3a96c</string>
                        <key>MetadataURL</key>
                        <string>https://swdist.apple.com/content/downloads/25/13/031-17334/o1b83gtjckvj2yvhdx1v3sz0nrpta28tjv/RicePaper-FoldedCard_E6C737BA-9C4A-4693-82F7-A3EE22555C4D.pkm</string>
                        <key>URL</key>
                        <string>

**Comment by kennyedgar** [comment]
I am also seeing the same issue when running a repo_sync

**Comment by gregneagle** [comment]
This has been discussed a few times on the reposado Google Groups mailing list and is Linux-Bistro specific.

https://groups.google.com/d/topic/reposado/_fUl1n3uPq8/discussion

and specifically, https://groups.google.com/d/msg/reposado/_fUl1n3uPq8/dobauIM0CAAJ

**Comment by kennyedgar** [comment]
Greg, very much appreciated!  Hopefully this will make it into the git repo?

**Comment by gregneagle** [comment]
Since it's Linux-distro specific, what exactly would make it into the git repo? There's no one change that will work for everyone.

**Comment by kennyedgar** [comment]
Greg, understood, and thanks again!

**Comment by igroykt** [comment]
@gregneagle thank! it work now =)
