### ISSUE TITLE
Change rewrite conditions for OSX 10.11 in nginx.conf

### ISSUE THREAD

**Issue by branzo** [wdas/reposado#40]
Good morning, 

i verified tomorrow that El Capitain clients do ask for catalogs.sucatalog instead of index(.*).sucatalog, so i think that the correct rewrite should be:

 if ( $http_user_agent ~ "Darwin/15" ){
  rewrite ^/index(.*)\.sucatalog$ /content/catalogs/others/index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1$1.sucatalog last;
}

and not the one reported in docs/URL_rewrites.md file.

**Comment by gregneagle** [comment]
No, the documented rewrites are correct and working for lots of people, myself included.

El Capitan clients by default query _Apple's_ servers. To get them to query your Reposado server you need to use MCX, a configuration profile, or `defaults` scripting to set a custom CatalogURL in the com.apple.SoftwareUpdate preferences domain.

This CatalogURL can take any form:
`http:/mysus.pretendco.com/where_are_my_updates.xml` could be a perfectly valid CatalogURL, as long as that URL returns the appropriate catalog data.

The catalogs hosted on Apple's servers are available at:

```
http://swscan.apple.com/content/catalogs/index.sucatalog
http://swscan.apple.com/content/catalogs/index-1.sucatalog
http://swscan.apple.com/content/catalogs/others/index-leopard.merged-1.sucatalog
http://swscan.apple.com/content/catalogs/others/index-leopard-snowleopard.merged-1.sucatalog
http://swscan.apple.com/content/catalogs/others/index-lion-snowleopard-leopard.merged-1.sucatalog
http://swscan.apple.com/content/catalogs/others/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
https://swscan.apple.com/content/catalogs/others/index-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
https://swscan.apple.com/content/catalogs/others/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
https://swscan.apple.com/content/catalogs/others/index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
```

If you _want_ to make your URLs have "catalogs.sucatalog" in them you can if you want, but we'll leave the "official" documentation as-is.

Here are the URL references inside the SoftwareUpdate binary in 10.11.3:

```
% strings /System/Library/PrivateFrameworks/SoftwareUpdate.framework/SoftwareUpdate | grep http
https://swscan.apple.com/content/catalogs/others/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
https://swscan.apple.com/content/catalogs/others/index-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
https://swscan.apple.com/content/catalogs/others/index-mountainlionseed-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
https://swscan.apple.com/content/catalogs/others/index-10.9seed-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
https://swscan.apple.com/content/catalogs/others/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
https://swscan.apple.com/content/catalogs/others/index-10.10seed-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
https://swscan.apple.com/content/catalogs/others/index-10.10beta-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
https
https://swscan.apple.com/content/catalogs/others/index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
http
https://validation.isu.apple.com/downloads/DevKey.plist
```
