### ISSUE TITLE
Enhancement: Option to automatically remove config-data on downloaded updates

### ISSUE THREAD

**Issue by poundbangbash** [wdas/reposado#41]
I'm excited for the munki change allowing unattended Apple updates discussed here https://groups.google.com/d/msg/munki-dev/o6WtjFOL74k/kT36MAOPDgAJ

In the current workflow removing the config-data is tedious as the admin needs to go thru updates and understand which updates have config-data.  Some are obvious, like XProtect and Gatekeeper, but some sneak up, like the recent MRT configuration update. 

The enhancement I'm proposing is an option/preference that would allow all newly downloaded updates to have its config-data removed at the time it is downloaded from Apple and brought into reposado.  I realize it shouldn't be the default as reposado is cloning the Apple SUS experience. I see the option being a key in the reposado preferences.plist to enable the feature for admins that want it.

I may be missing an obvious reason to leave the config-data intact but since cli softwareupdate doesn't see it until the config-data is removed as discussed in https://managingosx.wordpress.com/2015/01/30/gatekeeper-configuration-data-and-xprotectplistconfigdata-and-munki-and-reposado-oh-my/ the need for it seems diminished.

**Comment by gregneagle** [comment]
It definitely needs to stay an option and not become default behavior as not everyone is using reposado with Munki. Casper users using NetSUS might be surprised at unexpected new behavior, for example.

**Comment by flammable** [comment]
I'd use this feature, too.  My current script for accomplishing this is based on this gist:

https://gist.github.com/MiqViq/4dbe0210671aa80b2e8c

However, updates with config-data have grown past XProtect and Gatekeeper.  I'd like to make sure I'm covering them all.

Thanks!

**Comment by gregneagle** [comment]
Here's an attempt:
https://github.com/wdas/reposado/commit/3e4e3c287827fa0d2bd3e7f3d90407d645e7a0cc

With this change, you can call `repo_sync --remove-config-data` and all products will be checked for config-data attributes; if the attribute is there, it is removed.

Is this the right place for this? Should this be in `repoutil` instead?

**Comment by flammable** [comment]
Thanks, Greg!  I think this will do the job perfectly!

I agree, `repoutil` might be a better place for it.  Since we're manipulating data downloaded from Apple, `repo_sync` might not make the most sense (since it's not synching anything).  That said, if `repo_sync` is the easiest place to implement this, it's obviously your call. :)

**Comment by gregneagle** [comment]
I had second thoughts about this and have removed the option from `reposync`. The `--remove-config-data` option for `repoutil` now accepts a special product identifier 'all' which causes it to examine all products for the attribute and remove it if found. 
https://github.com/wdas/reposado/commit/37f31b412a5b1a9bb60f16f2572290379d1cb053

**Comment by flammable** [comment]
Works great, Greg!  Thanks!

**Comment by poundbangbash** [comment]
I'm curious to hear the second thoughts on pulling it out of repo_sync.

My thought on the ER was that it would be part of the sync process from Apple to the reposado server at the time it was copied.  The function being available as part of the sync lets those that wish to have config-data removed on acquisition run `repo_sync --remove-config-data` as part of their scheduled (or manual) sync.  

Yes, I understand there is still a step to get the new updates from the Apple catalog into a testing or production branch so `repoutil` would get involved at some point.  I use Margarita to make those changes  in our environment so I'll need to ask nice there, too, to incorporate these changes if `repoutil` is the home for the new option.

**Comment by gregneagle** [comment]
So do this on a schedule:

```
repo_sync
repoutil --remove-config-data all
```

Same end-result.

**Comment by gregneagle** [comment]
I'm going to close this on the assumption/belief that the `repoutil --remove-config-data all` approach satisfies the need here.
