### ISSUE TITLE
Repo_sync - HTTP result 200: Connection established

### ISSUE THREAD

**Issue by snowwalker1988** [wdas/reposado#42]
Since a few days I get this when I run the repo_sync:

> repo_sync run started
> Could not replicate https://swscan.apple.com/content/catalogs/others/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog: HTTP result 200: Connection established
> Could not replicate https://swscan.apple.com/content/catalogs/others/index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog: HTTP result 200: Connection established
> repo_sync run ended

I don't know why. Because I changed nothing.
What means the HTTP result 200?

Please can you help me?

**Comment by gregneagle** [comment]
This appears to be additional headers inserted by a proxy of some sort. Since I don't use a proxy, I can't replicate this. The good news is that another reposado user has a similar environment and we may have a fix soon.

**Comment by jessepeterson** [comment]
Submitted @gregneagle's patch as PR #45

**Comment by jessepeterson** [comment]
@snowwalker1988: can you test the latest version of reposado to see if this issue is resolved for you now? PR #45, above, should have solved it but also #47 has now been merged. Please let us know so we can close the ticket. Thanks!

**Comment by snowwalker1988** [comment]
Yes I will test it. Can I update reposado by only copying the new files into my reposado directory?

**Comment by gregneagle** [comment]
Yes.

**Comment by snowwalker1988** [comment]
Now I have tested the new version and I can say that the issue is resolved for me.
The failure isn't there anymore.
Thanks for your help!
