### ISSUE TITLE
OS X Sierra URL Not Supported

### ISSUE THREAD

**Issue by marcodesantis71** [wdas/reposado#53]
HI,

I configured all on my OS X Server.
I have a problem with the client running OS X Sierra.

When I try to check for update, I have "URL not supported" error.

Any suggestion?

I pointed my client to:

sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate CatalogURL http://su.myserver.com:80/index.sucatalog

with .htaccess file

**Comment by gregneagle** [comment]
What are the results of the testing you've done, following this documentation? https://github.com/wdas/reposado/blob/master/docs/URL_rewrites.md#testing

```
% curl --user-agent "Darwin/16.1.0" http://su.myserver.com:80/index.sucatalog > /tmp/testing
```

**Comment by marcodesantis71** [comment]
Hi.

in attach.
[testing.txt](https://github.com/wdas/reposado/files/571725/testing.txt)

**Comment by gregneagle** [comment]
```
	<dict>
		<key>031-02368</key>
		<dict>
			<key>Distributions</key>
			<dict>
				<key>English</key>
				<string>su.myserver.it/content/downloads/05/56/031-02368/a0h5nceqb9kjzzs3eus566vngukimq9j86/031-02368.English.dist</string>
```

That final string should be a URL.
Looks like you did not properly set LocalCatalogURLBase, which also needs to be a URL.
https://github.com/wdas/reposado/blob/master/docs/reposado_preferences.md#reposado-preferences
https://github.com/wdas/reposado/blob/master/docs/getting_started.md#getting-started-with-reposado
A LocalCatalogBase of "http://us/myserver.it" would result in that final string being

"http://su.myserver.it/content/downloads/05/56/031-02368/a0h5nceqb9kjzzs3eus566vngukimq9j86/031-02368.English.dist"

Is the 031-02368.English.dist file available from that URL?

**Comment by marcodesantis71** [comment]
Hi gregneagle,

thanks. Now It's ok.

I forgotten "http://" before the FQDN.
I reconfigured it and now it's works.

Thanks again

**Comment by gregneagle** [comment]
Closing.
