### ISSUE TITLE
Repo_sync - HTTP result 200: Connection established - again

### ISSUE THREAD

**Issue by hardtimes** [wdas/reposado#56]
I am seeing this as well with the latest repo_sync.  We do have microsoft's TMG proxying by a parent entity.  I have no access to it or insight into its configuration.  Suggestions?

Feb 01 09:43:07 Downloading 694 bytes from https://swdist.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/PaperSnowflakes-FoldedCard_Preview.pkm...
Feb 01 09:43:08 Downloading 685 bytes from https://swdist.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/HolidayGifts-FoldedCard_Preview.pkm...
Feb 01 09:43:08 Downloading 413002 bytes from http://swcdn.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/Mosaic-Postcard.pkg...
Feb 01 09:43:08 Downloading 413002 bytes from http://swcdn.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/Mosaic-Postcard.pkg...
Feb 01 09:43:08 WARNING: No body provided; assuming already downloaded for /srv/SUS/html/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/Mosaic-Postcard.pkg
Feb 01 09:43:08 Downloading 628 bytes from https://swdist.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/Mosaic-Postcard.pkm...
Feb 01 09:43:08 Downloading 628 bytes from https://swdist.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/Mosaic-Postcard.pkm...
Feb 01 09:43:09 Downloading 326982 bytes from http://swcdn.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/HangingOrnaments-FoldedCard_Preview.pkg...
Feb 01 09:43:09 Could not replicate http://swcdn.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/HangingOrnaments-FoldedCard_Preview.pkg: Error -5: Expected 326982 bytes, got: 18175
Feb 01 09:43:09 Downloading 326982 bytes from http://swcdn.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/HangingOrnaments-FoldedCard_Preview.pkg...
Feb 01 09:43:09 Could not replicate http://swcdn.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/HangingOrnaments-FoldedCard_Preview.pkg: HTTP result 200: OK
Feb 01 09:43:09 Downloading 376137 bytes from http://swcdn.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/XmasLights-FoldedCard_Preview.pkg...
Feb 01 09:43:09 Could not replicate http://swcdn.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/XmasLights-FoldedCard_Preview.pkg: Error -5: Expected 376137 bytes, got: 18174
Feb 01 09:43:09 Downloading 376137 bytes from http://swcdn.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/XmasLights-FoldedCard_Preview.pkg...
Feb 01 09:43:09 Could not replicate http://swcdn.apple.com/content/downloads/42/50/031-30754/ay4q41mkptevrm0p60cd4fdnp00gb1hd6f/XmasLights-FoldedCard_Preview.pkg: HTTP result 200: OK

**Comment by gregneagle** [comment]
I have no suggestions since I have no idea what "microsoft's TMG proxying by a parent entity" means, and since you "have no access to it or insight into its configuration" I doubt it would matter if I did.

You might consider posting on the reposado discussion list: http://groups.google.com/group/reposado

**Comment by hardtimes** [comment]
Sorry to post in the wrong place.  Some how multiple repo_sync instances became running(four of them) at the same time which is the only thing I can think of that caused this since when I killed all running instances of python the sync no longer showed either message and I was able to resync the vast majority of the repos without problem.

**Comment by gregneagle** [comment]
Great. I still encourage using the reposado discussion list -- you are more likely to reach someone who might have a similar configuration/experience. Posting here is likely to be seen by only me, and is best used for reproducable code issues.
