### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hardtimes** [wdas/reposado#57]
Not sure where else to put this.  When tailing the log, the "Downloading etc etc etc" message doesn't appear until after the download has occurred.  So in the case of large files that may take multiple minutes to download, one has no idea if anything is actually happening without opening a second utility like iotop.  If possible it would be nice to have the message written to the log before the even occurs.

example, below took ~10 minutes to display because it didn't show until after the download happened:
Feb 01 10:42:42 Downloading 438188881 bytes from http://swcdn.apple.com/content/downloads/05/34/031-12187/t614kl532jwk6pqkri5uzvmv3rmsnfcb3r/BootCampESD.pkg...

**Comment by gregneagle** [comment]
Years of use with lots of people point to this not really being a problem; most people just let repo_sync run and look at the results later (or have the results mailed to them, etc).
