### ISSUE TITLE
Issue with adding High Sierra 

### ISSUE THREAD

**Issue by blackberryhell** [wdas/reposado#61]
Team

I am trying to update reposado to include updates for High Sierra, the issue I am running into is the new catalog for High Sierra does not appear to create, I edited the .htaccess file and my client can see that change judging from the messages I am getting back

bash-3.2# curl --user-agent "Darwin/17" http://mydomain.com:8088/index.sucatalog > /tmp/release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   324  100   324    0     0  26470      0 --:--:-- --:--:-- --:--:-- 27000
bash-3.2# tail -5 /tmp/release
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1_production.sucatalog was not found on this server.</p>
</body></html>

I have checked the settings on the webserver and they seem to be correct and I've tried a manual repo sync but that doesn't see the catalog either. If you could tell me what glaringly obvious thing I am missing I would be very grateful.

Regards

Alex

**Comment by gregneagle** [comment]
This is not a support forum. Please post on http://groups.google.com/group/reposado.
