### ISSUE TITLE
The operation couldn’t be completed. (NSURLErrorDomain error -1100.)

### ISSUE THREAD

**Issue by jeolsen** [wdas/reposado#66]
I'm not sure if I'm missing a step.  But I've setup Reposado and Margarita on macOS 10.13.6.  I can see 1788 updates listed in Margarita, and the repo_sync finishes successfully.  I'll run this command to point to my software update catalog:

$ sudo softwareupdate --set-catalog https://<SERVER.DOMAIN>/reposado/html/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1_testing.sucatalog

I can even browse that in safari and it shows the XML.

But when I try to list updates I get an error:
$ softwareupdate --list --verbose
Software Update Tool

Finding available software
The operation couldn’t be completed. (NSURLErrorDomain error -1100.)

I see the same error if I use the AppStore to look for updates.  It had been working when I had used the Apple SUS on Sierra.  Am I missing something?

**Comment by gregneagle** [comment]
This type of discussion really belongs on the reposado discussion group: 
http://groups.google.com/group/reposado

Almost certainly you've supplied an invalid or inaccurate LocalCatalogURLBase in reposado's preferences and so the catalogs have invalid or inaccurate product URLs.

If you need to ask follow up questions, please post on the reposado group. You'll find this topic has been discussed there a few times and will find additional details in the archives.
