### ISSUE TITLE
RFE: repoutil --add argument order problem

### ISSUE THREAD

**Issue by mstarostik** [wdas/reposado#74]
The order of arguments to repoutil --add et al. is a little unlucky with BRANCH_NAME coming last. If it was the first argument, one could easily use xargs to add a bunch of products to a branch in one go.
Surely it would break any script out there to just reverse the logic, but maybe it could be added as an alternative along the lines of the -t argument to GNU cp, mv etc.
Use case: I have a scriptlet that parses the catalog and prints the ids of all products for 10.1[34]  so I can --add them for the chained-reposado-pattern to only download what's relevant on our site.
Workarounds abound, yet it would be one of those little things that make life a little more comfy.

**Comment by gregneagle** [comment]
Agree that this could have been designed better from the start. It's unlikely I'll fix it -- I'd have to add _new_ options so as not to break current usage patterns. But Apple has deprecated the setting of custom sucatalogs and I expect that within a year reposado will not be useful on Apple's (then) current OS. It's therefore hard to justify putting any but the most urgent work into reposado.

**Comment by gregneagle** [comment]
Closing as won't do.
reposado won't be getting any new features as Apple has made it unusable in Big Sur (as expected).
