### ISSUE TITLE
./repoutil --deprecated

### ISSUE THREAD

**Issue by SashLi** [wdas/reposado#75]
Running 

`
./repoutil --deprecated
`
on macOS 10.14 with Python 2.7.10 lead to 

```
Traceback (most recent call last):
  File "./repoutil", line 743, in <module>
    main()
  File "./repoutil", line 701, in main
    list_deprecated(sort_order=options.sort, reverse_sort=options.reverse)
  File "./repoutil", line 271, in list_deprecated
    list_products(sort_order, reverse_sort, list_of_productids)
  File "./repoutil", line 327, in list_products
    product_list.sort(key=lambda item: item['sort_key'], reverse=reverse_sort)
TypeError: an integer is required
```

Does anyone have an idea why ?

**Comment by skull4d** [comment]
Try adding python to access Full Disk Access in Security & Privacy > Privacy

**Comment by SashLi** [comment]
> Try adding python and Terminal to access Full Disk Access in Security & Privacy > Privacy

Does not change anything ... same error

**Comment by gregneagle** [comment]
Work is being done to make reposado compatible with Python 3 -- but recent commits broke things. I've moved that work to a new py3compatibility branch and reverted the commits in master. Pull the current master and try again.

**Comment by gregneagle** [comment]
Should be addressed in py3compatibility branch as well.

**Comment by SashLi** [comment]
Should I leave this open for the py3compatibility branch ?. 
Error is gone with the old sources.

**Comment by gregneagle** [comment]
I think it can be closed because https://github.com/wdas/reposado/issues/75#issuecomment-510882852

**Comment by SashLi** [comment]
Thanks for your help !
