### ISSUE TITLE
Unable to configure Mac OS X 11 Big Sur correctly

### ISSUE THREAD

**Issue by ronnybremer** [wdas/reposado#82]
We are using Reposado for quite a while now and since the switch to 11.0 our clients can no longer talk to the caching server. I managed to add the catalog and I can retrieve the content via curl, however, softwareupdate always returns:
The operation couldn’t be completed. (NSURLErrorDomain error -1012.)

I tried to change the repository URL in the preferences file to use HTTPS, to no avail. The catalog looks correct though.

Does anyone use this setup already?

**Comment by ronnybremer** [comment]
It looks like this was a planned change. From what I read in many forums and blogs today, Big Sur and onward will no longer allow access to a local cache, unless we use the new "Caching" feature inside of Mac OS X.

**Comment by gregneagle** [comment]
Yes. Added a note to the read me for Mac admins that have missed this change.
https://github.com/wdas/reposado/blob/main/README.md
